### ISSUE TITLE
Reduce Performance Impact of Furnaces

### ISSUE THREAD

**Issue by wingzero54** [CivMC/FactoryMod#12]
Furnace tile entities consistently use 1% of server performance. Easily replicated by running a Spark profile when running factories. I don't have any spark profiles on hand because they get deleted. tl;dr is the furnaces on factories are constantly looking for inputs and it seems silly to lose even 1% of server performance for furnaces to glow when factories run. 

Not sure what/ if there is a solution

Timing for reference: https://timings.aikar.co/?id=f2937ef970784b3a833a7dd7c75075ef

**Comment by Maxopoly** [comment]
That's a vanilla minecraft thing and part of the reason why placing tile entities (not only pistons) needs to be limited. It's entirely unrelated to FactoryMod.
