### ISSUE TITLE
Make secure notes more user friendly

### ISSUE THREAD

**Issue by wingzero54** [CivMC/FactoryMod#13]
Secure notes currently use 32 digit codes which are not very user friendly - and hard to compare notes for authenticity at a glance. Can we reduce the number of characters, or do some combination of citadel group + code to make more user-friendly secure codes while still maintaining security? 

Example secure note below: 
![image](https://user-images.githubusercontent.com/7980903/160891487-660bc958-7590-4c9a-bdb6-f1b2362d946b.png)

**Comment by Maxopoly** [comment]
There are two ways I can think of realizing this:
The first one is generating more user friendly random output, something like gfycat's URL generation where it takes random adjectives: [selfreliantsimilargrebe](https://gfycat.com/selfreliantsimilargrebe)
The other one would be allowing users to chose their tag. That would require a permission based system of uniqueness, which makes tying it into NameLayer the easiest solution. Would more than one code per group be desireable or is using the group name as code sufficient?

**Comment by wingzero54** [comment]
It's hard to know, is there likely to be more than one maker using the same factories or groups? Would group + short code like HJI-c71f suffice to allow multiple codes per group with reasonable expectation that someone else on your group won't try to copy you? Could also result in people re-rolling secure plates until they get one with a suffix they like (HJI-1234) but that is probably getting into more wordbank-y solutions

**Comment by Maxopoly** [comment]
Well the group doesn't have to be the one the factory is reinforced on, just one the person running it has sufficient perms on. I am not actually sure how secure notes even work, but if someone makes a proper feature spec of how they want it to work I can implement it.

**Comment by Lodish** [comment]
I'd be a fan of the character's being reduced, the long code stretches the note out, for instance I never used secure notes for CivTCG cards (risking someone making forfeit cards) because how bad the stretching made the cards look. An 8 digit code would still have 2,612,182,843,000 combinations

**Comment by wingzero54** [comment]
Considering using brute force to duplicate a secure printing plate isn't as easy as computing the combinations, 8 hex characters do have a pretty high level of entropy. What do you think Max? Creating millions of secure printing plates trying to find a collision would be pretty crazy, but then again there are crazy people that play civ

**Comment by wingzero54** [comment]
Looks like right now the secure note code is just the uuid of the book used to make the printing plate

**Comment by Lodish** [comment]
> Looks like right now the secure note code is just the uuid of the book used to make the printing plate

err are you sure? I could have sworn if you make more than one plate from the same book they all have different codes. I could be wrong though.

**Comment by Maxopoly** [comment]
8 Hex characters is 32 bit, which is trivial to brute force offline (only need a few plates for that as reference). 
Would be fine if we use sufficient input entropy though, for example hashing the UUID and some secret seed from the config.

**Comment by Gjum** [comment]
doesn't have to be hex, 8 digits base64 gives 48 bits, and we can even use special chars with less horizontal width like `|iIl,.:;'`

we can also hide the identifier completely (different nbt key, not lore)

human friendly validation could be done through some command, for example `/checkhelditem $namelayergroup` tells you that the item was made through a process that requires the creator having some "secure_note" permission in that nl group

**Comment by wingzero54** [comment]
> 8 Hex characters is 32 bit, which is trivial to brute force offline (only need a few plates for that as reference). Would be fine if we use sufficient input entropy though, for example hashing the UUID and some secret seed from the config.

I think this is the best option, let's add a secret config seed to hash the UUID's into 8 hex characters. Going off #14 , would this enable us to secure stamp other items as well using their UUID?

**Comment by Lodish** [comment]
> which is trivial to brute force offline

I'm not sure what this would even mean, how do you brute force running a factory recipe offline?
I'm not even sure its a problem if someone could expend a huge amount of charcoal, iron and time on the chance of making a perfect counterfeit.

> human friendly validation could be done through some command, for example /checkhelditem $namelayergroup tells you that the item was made through a process that requires the creator having some "secure_note" permission in that nl group

What does a namelayer group have to do with anything? I think what is effectively checking the stamp on a physical good is much more intuitive than a command.
