### ISSUE TITLE
Wordbank does not work

### ISSUE THREAD

**Issue by wingzero54** [CivMC/FactoryMod#3]

**Comment by Diet-Cola** [comment]
Imo, Remove this feature and re-implement O.G Wordbank. The only reason for FM Wordbank was cause Amel found a pattern get specific colors for words iirc

**Comment by Maxopoly** [comment]
Define "does not work"

**Comment by Diet-Cola** [comment]
Iirc the recipe stopped working after implemented, I'd imagine due to a internal change from cmc, the word bank will never recognise there is an item to generate for

**Comment by wingzero54** [comment]
Any combination of inputs always results in an error from the recipe and the recipe never runs and finishes. I don't recall the exact error, "no valid inputs" or something.

**Comment by Diet-Cola** [comment]
My thoughts are still updating O.G Wordbank

**Comment by Diet-Cola** [comment]
Fixed by https://github.com/CivMC/FactoryMod/pull/20
